#☑️ **프로젝트 주제**

###걷기 좋은 광진을 위한 보행환경개선지구 선정: 서울시 보행환경개선지구 사례를 바탕으로

---

#📌 **프로젝트 목적**

- 광진구는 「보행안전 및 편의증진에 관한 법률」에 따라 중곡동과 구의2동을 대상으로 보행환경개선지구 사업을 진행함.

- 보행환경개선사업을 통한 보행의 회복은 단순히 보행자의 안전 뿐만 아니라 도시 공간의 활력을 불러올 수 있음.

- 더 나아가 보행활동을 통한 집합적인 장소경험의 공유는 집합적인 지역의 이미지를 공유하여 지역공동체를 묶어주는 ‘공동체의식’을 이끌어 냄. 또한 기후변화, 저탄소 정책, 보행약자의 이동권 보장 등 다양한 사회적 요구를 수렴하여 지속 가능한 도시공간체계로의 변화를 도모하기 위해서는 걷고 싶은 도시가 가지는 잠재력을 고려해야 함.

  - _원활한 보행 이동이 보장된다면 보행과 대중교통만으로도 구 내 이동이 가능하기 때문에 불법주정차 및 상습적인 정체 현상은 감소할 것으로 기대됨. 그리고 이면도로가 많은 광진구에서 보행환경개선사업이 원활히 진행된다면 휠체어 등을 이용하는 장애인 등 노약자의 보도 이동권이 보장될 것으로 사료됨._

- 광진구가 지속가능한 도시로서 발돋움하기 위해서는 보행환경개선사업이 일회성 사업으로 전락하지 않도록 지속적인 관심과 투자, 철저한 사후 관리가 필요함.

- 본 프로젝트는 기존 광진구에서 진행한 두 곳과 다른 자치구의 보행환경개선지구를 바탕으로 사업 전과 후의 보행환경이 정량적으로 얼만큼 개선되었는지 파악하고자 함. 이를 위해 **보행환경을 평가할 수 있는 변수를 설정**하고 통계기법을 활용하고자 함. 이후 광진구 내 보행환경 개선이 시급한 구역을 선정하고 세부적인 효과까지 도출하는 프로젝트를 진행하고자 함.

___


#📌 **프로젝트 흐름**
###**I. 변수 선정**

변수 선택 알고리즘을 이용하기 위해서는  
**독립변수**와 **종속변수**가 필요함. 

서울시 전체 사업지의 사례 이용하여 다양한 변수 선택 알고리즘을 통해 모든 알고리즘에서 적절하다고 판단한 변수 
→ 변수 최종 선정 → 변수의 가중치 계산

독립변수: 사업지 전과 후의 변수 데이터셋 구축

종속변수: 사업 전과 후의 해당 지역에서의 보행자 안전사고 발생 건수

⇒  변수의 가중치 계산(데이터셋에 맞는 적절한 알고리즘 활용 필수)


###**II. 광진구 동별 변수 데이터 세팅**


###**III. 클러스터링 진행**
엘보우 메소드(다른 알고리즘도 고려) 진행하여 적절한 클러스터 개수 도출 → 클러스터링(K-Means 등) 진행 후 중심점(centroid) → 클러스터 간 차이 파악(각 클러스터마다 어떤 변수가 중요하게 작동했는지 등) → 각 클러스터 지도에 표현


###**IV. 광진구 내 사업지 추출**
보행환경이 낮다고 판단한 클러스터 추출 → 특정 필수 조건(어린이보호구역 필수 포함과 같은!) 적용하여 최종 사업 구역 확정


###**V. 사업 효과 분석**

---

#**I. 변수 선정**
- 서울특별시 도시교통본부 보행자전거과에서 제공한 보행환경 관련 보도자료에 첨부된 '보행환경 개선지구' 목록을 이용하였음. 
- 해당 자료는 '13~'15년에 사이에 진행된 사업지구이므로 사업 진행 이후로 7년 이상의 시간이 지나 사업의 효과를 바탕으로 변수 선정의 타당성을 파악하기에 적절하다고 판단함.

### 1. **종속변수**
[사업 직전 3개년('10 -'12) 각 동의 차대사람 교통사고 수] - [사업 이후 최근 3개년('19 -'21) 각 동의 차대사람 교통사고 수]

### 2. **임시 독립변수**
A. 경사도 (완료)

B. 지하철 이용객 (660m 반경) [15년과 19년 비교]

C. 범죄안전(CCTV 개수) [15년과 19년 비교]

D. 보행약자 통행 공간 (연속적 보행 가능성)

E. 유동인구 [16년과 19년 비교]

F. 불법주정차 단속 건수 [15년과 19년 비교]

G. 차량통행속도

H. 가로유형

I. 연속적 보행환경

J.매츨 [13-15와 16-19 비교]




---

## 📌**변수의 타당성을 파악하기 위한 기존 보행환경 개선지구**

####**1. 중구 명동 보행환경 개선지구**

→ 을지로2가, 남대문로2가, 충무로1,2가, 명동1,2가, 저동1가

####**2. 용산구 세계음식문화거리 보행환경 개선지구**

→ 이태원동

####**3. 성동구 서울숲길 주변 보행환경 개선지구**

→ 성수동1가

####**4. 광진구 구의강변로 보행환경 개선지구**

→ 구의동

####**5. 송파구 석촌동 보행환경 개선지구**

→ 석촌동

####**6. 강동구 강풀만화거리 보행환경 개선지구**

→ 성내동

ref. 명동같은 경우는 상업구역이 특정 동에만 국한되지 않아 사업지역이 여러 동에 걸쳐있다고 판단함.

따라서, 각 동에 해당하는 변수의 데이터를 이용하고자 함. 또한 프로젝트에서는 각 보행환경 개선지구가 포함되어 있는 행정동을 그룹명으로 사용하였음. (e.g 송파구 석촌동 보행환경 개선지구: 석촌동)

## **보행환경 개선사업이 진행되지 않은 법정동 선정**

#### 보행환경 개선사업이 진행된 곳과 진행되지 않은 곳의 데이터셋을 구축하여 보다 보행환경 개선사업의 효과를 입증하기 위함

In [ ]:
import random
import csv

# 기존 보행환경 개선사업이 진행된 법정동을 제외한 서울시 법정동 CSV 파일에서 법정동 이름을 불러온다.
with open('/content/drive/MyDrive/법정동코드 조회자료.csv', 'r', encoding='cp949') as file:
    csv_reader = csv.reader(file)
    all_dongs = [row[1] for row in csv_reader]

# 6개의 동을 무작위로 추출한다.
random_dongs = random.sample(all_dongs, 6)

# 추출된 6개의 동을 출력한다.
print("랜덤으로 선택된 6개의 동: ")
for dong in random_dongs:
    print(dong)

- 서울특별시 강남구 압구정동

- 서울특별시 마포구 노고산동

- 서울특별시 종로구 사직동

- 서울특별시 서대문구 미근동

- 서울특별시 영등포구 문래동4가

- 서울특별시 노원구 상계동

##**I-1. 종속변수**
[사업 직전 3개년('10 -'12) 각 동의 차대사람 교통사고 수] - [사업 이후 최근 3개년('19 -'21) 각 동의 차대사람 교통사고 수]

    - TAAS에서 제공하는 교통사고 데이터를 이용함.
    - 각 동이 속해 있는 자치구의 사고 데이터를 추출 후, 시군구 컬럼에서 해당 동의 사고 데이터만 추가 추출 진행

    증감율 = (최종 수치 – 최초 수치)/최초 수치×100

|그룹명|'10-'12 사고|'19-'21 사고고|차대사람 교통사고 증감율(%)|
|------|---|---|---|
|을지로2가|10|23|+130|
|남대문로2가|3|4|+33.33|
|충무로1가|28|14|-50|
|충무로2가|17|12|-29.41|
|명동1가|41|4|-90.24|
|명동2가|13|11|-15.38|
|저동1가|17|4|-76.47|
|이태원동|98|107|+9.18|
|성수동1가|110|103|-6.38|
|구의동|268|130|-51.49|
|석촌동|150|118|-21.33|
|성내동|228|191|-16.23|

#**I-2. 독립변수**
##**A. 경사도**

- 국가공간정보포털의 DEM (90M)를 사용해도 가능하나, 90 x 90m로 간격이 큰 편이어서 동 규모에 사용하기에는 다소 거칠다. 
따라서 직접 국가공간정보포털에서 제공받은 수치지형도(1:5000)을 활용하여 10 x 10m 간격의 DEM을 생성하였다. 이를 QGIS에서 레스터를 백터로 변환한 경사도 데이터를 이용하였다. 

<사용한 데이터>

수치지형도 v2.0(1:5000)

출처: 국토지리정보원


![image](https://user-images.githubusercontent.com/129578708/230248425-9bf2f979-8462-42a1-aa64-cd2378653744.png)
Fig 1. 경복궁 일대 경사도 예시

|그룹명|경사도|
|------|---|
|을지로2가|5.867|
|남대문로2가|1.200|
|충무로1가|1.484|
|충무로2가|4.607|
|명동1가|4.660|
|명동2가|6.043|
|저동1가|6.222|
|이태원동|7.727|
|성수동1가|1.000|
|구의동|4.348|
|석촌동|0.500|
|성내동|3.750|

##**B. 지하철 이용객 (반경 660m)**

- 각 사업지역의 중심으로부터 반경 660m 내에 속한 지하철역의 이용객 수를 통해 **지역의 유동인구**를 유추하고자 한다. 

- 660m를 반경의 기준으로 삼은 근거는 아래와 같다.

_보행자의 평균 통행거리 및 인근 지하철역과의 거리 등을 고려하여 반경 약 660m(보행통행시간 약 10분) 을 적용함

ref. (최창규, 성현곤, 이수기, 김태현, 고준호, 원보환.(2013).[특집_주제] 지속가능 도시를 위한 보행활동 증진방안.도시정보,(373),3-22.)_

<사용한 데이터>

서울시 지하철호선별 역별 승하차 인원 정보
출처: 서울특별시 도시교통실 교통기획관 교통정책과

  * CARD_SUBWAY_MONTH_2015
  * CARD_SUBWAY_MONTH_2019



    1) 각 사업지역의 중심점을 생성

    2) 중심점으로부터 버퍼 660m 생성

    3) 버퍼 내 지하철 출입구 포함된 지하철역 취합

    4) 서울열린데이터광장에서 제공받은 '서울시 지하철호선별 역별 승하차 인원 정보' 활용

    5) 2015년, 2019년 데이터 사용
    (∵ 서울열린데이터광장에서 제공하는 데이터는 2015년부터임. 기존 보행환경 개선지구 사업이 2013~2015년 사이에 시작함. 
    따라서 2015년 데이터를 사용하고, 코로나19 발생 직전인 2019년의 지하철 이용객 수를 사용하여 보다 정확한 이용객 수의 증감을 알아보고자 함. )




![image](https://user-images.githubusercontent.com/129578708/230353253-6e5f2f2e-ab5f-4296-9549-915406d33c49.png)
Fig 2. 석촌동 보행환경 개선지구 중심점 반경 660m 예시


|그룹명|포함된 지하철역|
|------|---|
|을지로2가|을지로입구, 을지로3가, 종각, 명동|
|남대문로2가|을지로입구, 시청, 종각, 회현, 명동|
|충무로1가|명동, 회현, 시청, 을지로입구|
|충무로2가|명동, 충무로, 을지로3가, 을지로입구|
|명동1가|종각, 시청, 명동, 을지로3가, 을지로입구|
|명동2가|명동, 을지로3가, 을지로입구, 회현|
|저동1가|종각, 명동, 을지로3가, 을지로입구, 충무로|
|이태원동|이태원, 녹사평|
|성수동1가|서울숲, 뚝섬|
|구의동|구의, 강변|
|석촌동|석촌, 석촌고분|
|성내동|천호, 강동|

#### **B-1. 2015년**

In [ ]:
# 1. 데이터 로드
import pandas as pd
import numpy as np

data15 = pd.read_csv('/content/drive/MyDrive/CARD_SUBWAY_MONTH_2015.csv', encoding = 'cp949')

# 2. 그룹별 역명 지정
group_dict = {
    '을지로2가': ['을지로입구', '을지로3가', '종각', '명동'],
    '명동1가': ['종각', '시청', '명동', '을지로3가', '을지로입구'],
    '명동2가': ['명동', '을지로3가', '을지로입구', '회현'],
    '충무로1가': ['명동', '회현', '시청', '을지로입구'],
    '충무로2가': ['명동', '충무로', '을지로3가', '을지로입구'],
    '남대문로2가': ['을지로입구', '시청', '종각', '회현', '명동'],
    '저동1가': ['종각', '명동', '을지로3가', '을지로입구', '충무로'],
    '이태원동': ['이태원', '녹사평(용산구청)'],
    '성수동1가': ['서울숲', '뚝섬'],
    '구의동': ['구의', '강변'],
    '석촌동': ['석촌', '석촌고분'],
    '성내동': ['천호', '강동']
}

# 3. 그룹별 역명에 따라 일년 총 이용객수 계산
yearly_usage_dict = {}
for group_name, station_list in group_dict.items():
    group_df = data15[data15['역명'].isin(station_list)]
    total_usage = group_df['승차총승객수'].sum() + group_df['하차총승객수'].sum()
    daily_usage = total_usage / 365
    yearly_usage_dict[group_name] = daily_usage

# 4. 그룹별 일년 총 이용객수를 데이터프레임으로 생성
usage_df15 = pd.DataFrame.from_dict(yearly_usage_dict, orient='index', columns=['일평균 이용객'])
usage_df15.index.name = '그룹명'

# 인덱스를 컬럼으로 변환하고 컬럼명 수정
usage_df15 = usage_df15.reset_index().rename_axis('', axis=1)

usage_df15

       그룹명        일평균 이용객
0    을지로2가  335087.487671
1     명동1가  434185.246575
2     명동2가  304450.452055
3    충무로1가  345550.523288
4    충무로2가  312812.002740
5   남대문로2가  436156.331507
6     저동1가  403417.810959
7     이태원동   50100.243836
8    성수동1가   44017.049315
9      구의동  150610.956164
10     석촌동   18712.972603
11     성내동  121958.468493

#### **B-2. 2019년 (코로나19 발생 이전)**

In [ ]:
# 1. 데이터 로드
import pandas as pd
import numpy as np

data19 = pd.read_csv('/content/drive/MyDrive/CARD_SUBWAY_MONTH_2019.csv', encoding = 'cp949')

# 2. 그룹별 역명 지정
group_dict = {
    '을지로2가': ['을지로입구', '을지로3가', '종각', '명동'],
    '명동1가': ['종각', '시청', '명동', '을지로3가', '을지로입구'],
    '명동2가': ['명동', '을지로3가', '을지로입구', '회현(남대문시장)'],
    '충무로1가': ['명동', '회현(남대문시장)', '시청', '을지로입구'],
    '충무로2가': ['명동', '충무로', '을지로3가', '을지로입구'],
    '남대문로2가': ['을지로입구', '시청', '종각', '회현(남대문시장)', '명동'],
    '저동1가': ['종각', '명동', '을지로3가', '을지로입구', '충무로'],
    '이태원동': ['이태원', '녹사평(용산구청)'],
    '성수동1가': ['서울숲', '뚝섬'],
    '구의동': ['구의(광진구청)', '강변(동서울터미널)'],
    '석촌동': ['석촌', '석촌고분'],
    '성내동': ['천호(풍납토성)', '강동']
}

# 3. 그룹별 역명에 따라 일년 총 이용객수 계산
yearly_usage_dict = {}
for group_name, station_list in group_dict.items():
    group_df = data19[data19['역명'].isin(station_list)]
    total_usage = group_df['승차총승객수'].sum() + group_df['하차총승객수'].sum()
    daily_usage = total_usage / 365
    yearly_usage_dict[group_name] = daily_usage

# 4. 그룹별 일년 총 이용객수를 데이터프레임으로 생성
usage_df19 = pd.DataFrame.from_dict(yearly_usage_dict, orient='index', columns=['일평균 이용객'])
usage_df19.index.name = '그룹명'

# 인덱스를 컬럼으로 변환하고 컬럼명 수정
usage_df19 = usage_df19.reset_index().rename_axis('', axis=1)

usage_df19

       그룹명        일평균 이용객
0    을지로2가  334941.463014
1     명동1가  437141.528767
2     명동2가  311782.873973
3    충무로1가  345645.728767
4    충무로2가  312260.597260
5   남대문로2가  431587.189041
6     저동1가  398202.057534
7     이태원동   47254.128767
8    성수동1가   56289.000000
9      구의동  137533.068493
10     석촌동   38737.936986
11     성내동  118790.276712

In [ ]:
# 그룹명 컬럼을 기준으로 두 개의 데이터프레임을 merge
merged_df = pd.merge(usage_df15, usage_df19, on='그룹명', suffixes=('_15년도', '_19년도'))

# 일평균 이용객의 차이를 계산
merged_df['일평균 이용객 차이'] = merged_df['일평균 이용객_19년도'] - merged_df['일평균 이용객_15년도']

# 일평균 이용객 차이에 대한 증감율 계산
merged_df['일평균 이용객 증감율'] = round((merged_df['일평균 이용객 차이'] / merged_df['일평균 이용객_15년도']) * 100, 2)

In [ ]:
merged_df

       그룹명   일평균 이용객_15년도   일평균 이용객_19년도    일평균 이용객 차이  일평균 이용객 증감율
0    을지로2가  335087.487671  334941.463014   -146.024658        -0.04
1     명동1가  434185.246575  437141.528767   2956.282192         0.68
2     명동2가  304450.452055  311782.873973   7332.421918         2.41
3    충무로1가  345550.523288  345645.728767     95.205479         0.03
4    충무로2가  312812.002740  312260.597260   -551.405479        -0.18
5   남대문로2가  436156.331507  431587.189041  -4569.142466        -1.05
6     저동1가  403417.810959  398202.057534  -5215.753425        -1.29
7     이태원동   50100.243836   47254.128767  -2846.115068        -5.68
8    성수동1가   44017.049315   56289.000000  12271.950685        27.88
9      구의동  150610.956164  137533.068493 -13077.887671        -8.68
10     석촌동   18712.972603   38737.936986  20024.964384       107.01
11     성내동  121958.468493  118790.276712  -3168.191781        -2.60

### **유동인구**

<사용한 데이터>

서울시 50m간격 월별 kt 유동인구(2016년)

2016.05~08

서울시 내국인 kt 생활이동 데이터(2019년)


출처: 서울특별시 빅데이터 캠퍼스


      1. 유동인구 데이터가 50m 간격으로 블록을 구성하여 해당 블록별 유동인구를 산출하고 있음
      2. 해당 블록의 좌표를 5179좌표계로 설정하여 x,y 좌표 제공함
      3. 기존 사업구역 내 포함되는 블록의 좌표를 추출함
      4. 추출한 좌표만 데이터셋에서 추출함
      5. 이를 해당 월별 유동인구 합산에 이용함

##**C. 범죄안전: CCTV 개수**

<사용한 데이터>

서울시 CCTV 현황 공간데이터

출처: 서울특별시 빅데이터캠퍼스
    
    1) QGIS를 이용하여 CSV 파일을 지도상에 올림
    2) 폴리곤에 포함하는 포인트 개수 계산
    → 기존 보행환경 개선지구 폴리곤 내 위치한 CCTV 포인트 개수를 파악함



![image](https://user-images.githubusercontent.com/129578708/230347501-664d1b43-209c-4b88-b253-00a6671edae9.png)
Fig 3. 서울시 CCTV 분포 현황


![image](https://user-images.githubusercontent.com/129578708/230347247-6185399c-8dd2-46f4-b926-7e4055820ac7.png)
Fig 4. 석촌동 보행환경 개선지구 내 CCTV 분포 현황


|그룹명|'15 cctv 개수|'19 cctv 개수|증감율|
|------|:---:|:---:|---|
|을지로2가|2|4||
|남대문로2가|0|0||
|충무로1가|4|6||
|충무로2가|4|6||
|명동1가|4|7||
|명동2가|4|8||
|저동1가|6|8||
|이태원동|0|0||
|성수동1가|14|16||
|구의동|12|24||
|석촌동|30|55||
|성내동|2|4||

##**D. 보행약자 통행 공간**

- 보도 설치 및 관리 지침(2018.7.26. 국토교통부예규 제237호)에 따르면 '보도의 유효폭은 최소 2.0m 이상을 확보하되, 지형상 부득이한 경우에는 1.5m 이상으로 한다.'로 명시되어 있음.

- 또한 '보도의 유효폭은 보행자도로에서 보행자가 시설물에 방해받지 않고 이용하는 최소폭이므로 여유폭에 대한 고려가 필요하다'라는 법령에 따라 본 프로젝트에서는 전체 도로 면적 중 최소 폭 1.5m의 보도가 있는 면적의 비율을 나타내도록 함.

- 국토지리정보원에 문의한 결과, 해당 데이터셋은 보도폭 3m 이상인 보도를 대상으로 일괄 표현한 것으로 전달받았음.



<사용한 데이터>

- (도로명주소)실폭도로

  출처: 행정안전부

- 인도(보도)

  출처: 국토지리정보원


  ![image](https://user-images.githubusercontent.com/129578708/230750954-8f56d8c5-1da4-4f76-be71-03a866025ac4.png)
Fig 5. 서울시 전체 도로 현황


![image](https://user-images.githubusercontent.com/129578708/230750963-22e28e49-017f-4229-9827-df288f6bef06.png)
Fig 6. 서울시 인도(보도) 현황


![image](https://user-images.githubusercontent.com/129578708/230750919-b27a53bc-1435-4dc6-9639-e70b6c8b26ee.png)
Fig 7. 석촌동 보행환경 개선지구 내 전체도로 속성 테이블


![image](https://user-images.githubusercontent.com/129578708/230750925-898f0922-f1a0-407f-a250-3cd4bcdb1ce6.png)
Fig 8. 도로 면적용 함수식


![image](https://user-images.githubusercontent.com/129578708/230750931-13131e89-950e-429c-802b-bfaf4ccfc5cf.png)
Fig 9. 도로 면적 컬럼 생성성


![image](https://user-images.githubusercontent.com/129578708/230750935-6c8c8e31-f40c-493a-979a-9225932ca744.png)
Fig 10. 명동 보행환경 개선지구 내 도로(검은색) 및 보도(파란색) 현황


    1) QGIS를 이용하여 각 보행환경 개선지구 내 전체 도로와 보도를 추출함
    2) 추출된 도로와 보도의 면적을 계산함 (QGIS의 필드계산기: $area 함수 사용)
    3) 각 보행환경 개선지구별 (보도 면적/전체 도로 면적) X 100 계산함


|그룹명|전체도로 면적|보도 면적|비율|
|------|:---:|:---:|:---:|
|을지로2가|13736|3188|23.21|
|남대문로2가|6112|1585|25.93|
|충무로1가|9431|2397|25.42|
|충무로2가|10735|2165|20.17|
|명동1가|6864|1965|28.63|
|명동2가|15296|3277|21.42|
|저동1가|5053|1893|37.46|
|이태원동|1462|0|0|
|성수동1가|18079|1775|9.82|
|구의동|15099|1644|10.89|
|석촌동|48707|3580|7.35|
|성내동|8190|1|0.01|

##**E. 조경 (가로수)**

<사용한 데이터>

서울시 가로수 위치정보

출처: 서울특별시 푸른도시여가국 조경과


![image](https://user-images.githubusercontent.com/129578708/230566446-abd3c372-07bc-411c-ab32-cf4536f07eec.png)
Fig 5. 서울시 가로수 분포 현황


![image](https://user-images.githubusercontent.com/129578708/230567188-acb5ffe0-0a08-4955-ae98-334c1dbebc86.png)
Fig 6. 명동 보행환경 개선지구 가로수 분포 현황


|그룹명|조경 (가로수)|
|------|:---:|
|을지로2가|48|
|남대문로2가|34|
|충무로1가|18|
|충무로2가|17|
|명동1가|8|
|명동2가|25|
|저동1가|16|
|이태원동|0|
|성수동1가|76|
|구의동|34|
|석촌동|51|
|성내동|0|

## **G. 불법주정차 단속 건수** 

<사용한 데이터>

불법 주정차 단속 현황

출처: 서울특별시 빅데이터캠퍼스

'15 불법주정차 총 단속건수: 260,107 건

'19 불법주정차 총 단속건수: 504,215 건

|그룹명|'15 불법주정차 단속건수|'19 불법주정차 단속건수|증감율|
|------|:---:|:---:|---|
|을지로2가|12|27||
|남대문로2가|34|31||
|충무로1가|51|134||
|충무로2가|41|89||
|명동1가|0|16||
|명동2가|12|30||
|저동1가|38|16||
|이태원동|0|38||
|성수동1가|0|232||
|구의동|5|116||
|석촌동|8|31||
|성내동|2|25||

##**K. 매출**

<사용한 데이터>

서울시 블록단위 분기별 추정매출액

출처: 서울특별시(빅데이터캠퍼스)

- '13 -'15 서울시 블록단위 분기별 추정매출액과 '16 -'19 서울시 블록단위 분기별 추정매출액의 증감을 비교하고자 함.
이를 통해 보행환경 개선사업이 지역 경제 활성화를 이끌 수 있음을 확인해보고자 함.
- 해당 데이터는 동 단위가 아닌, 블록 단위이므로 기존 보행환경 개선사업 지역의 사업구역 폴리곤과 중첩되는 블록을 추출할 필요가 있음.
- 따라서 중첩되는 블록의 추정매출액을 사용함.


      1. 상기 추정매출액 데이터는 동 단위가 아닌 자제 제작한 블록단위로 구성되어 있음 (TBGIS_BLCK_RELM_INFO에 블록의 정보 및 shp 데이터가 있음)
      2. 기존 보행환경 개선사업 지역의 폴리곤과 블록이 중첩되는 부분을 추출함 (QGIS 내 '교차영역' 기능 사용)
      3. 중첩 구역의 dbf 파일을 csv 파일로 불러와 추정매출액 계산함

### **사용한 코드 (명동 지역 예시)**
#### **'13-'15 데이터와 '16-'19 모두 동일한 코드를 사용하였음**


```
import pandas as pd
from dbfread import DBF

# 추정매출액 txt 파일을 데이터프레임으로 불러옵니다.
df = pd.read_csv('th_ic_ecm_blck_selng_qu_2013_2015.txt', delimiter = '|', quotechar = " ' ", encoding = 'utf-8')

#sales_13_15는 df 중 필요한 컬럼만 추출하여 생성한 데이터프레임임.

# DBF 파일을 pandas 데이터프레임으로 읽어옵니다.
dbf = DBF('명동 매출 블록.dbf', encoding='utf-8')
df_dbf = pd.DataFrame(dbf)

# 필요한 블록코드를 선택합니다.
blk_cd_list = [160331, 206707, 206703]

# sales_13_15.csv 파일을 pandas 데이터프레임으로 읽어옵니다.
df_sales = pd.read_csv('sales_13_15.csv', encoding='cp949')

# 블록코드가 선택한 blk_cd_list에 속하는 데이터를 필터링합니다.
df_sales_selected = df_sales[df_sales['블록코드'].isin(blk_cd_list)]

# 필터링된 데이터에서 분기매출액을 총 합산합니다.
total_sales = df_sales_selected['분기매출액'].sum()
```

|그룹명|'13-'15 추정매출액(원)|'16-'19 추정매출액(원)|증감율|
|------|---|---|---|
|을지로2가|719,402,048,267|655,697,958,241|-8.86|
|남대문로2가|688,341,412,264|519,639,480,933|-24.51|
|충무로1가|1,367,766,049,543|1,015,878,971,997|-25.73|
|충무로2가|1,071,913,945,062|856,990,254,302|-20.05|
|명동1가|1,817,306,815,735|1,359,206,537,831|-25.21|
|명동2가|2,353,092,308,019|1,692,314,576,851|-28.08|
|저동1가|125,795,678,637|115,444,152,355|-8.23|
|이태원동|285,793,707,754|320,625,763,811|12.19|
|성수동1가|41,518,150,692|97,825,478,857|135.62|
|구의동|85,400,494,500|93,383,957,488|9.35|
|석촌동|191,829,664,513|221,312,161,945|15.37|
|성내동|151,375,967,670|188,316,877,849|24.40|